version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8802:8802"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - ENV_FILE=.env

  unstructured-api:
    image: downloads.unstructured.io/unstructured-api:latest
    ports:
      - "9500:8000"
    restart: always