"""
API routes for exporting data to Word format
"""
import os
import logging
from typing import Any, Dict, List, Optional
from datetime import datetime
from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import Response
from sqlalchemy.orm import Session

from app.db.session import get_db
from app.db.models import User
from app.api.deps import get_current_user
from app.services.docx_export import create_summary_docx

router = APIRouter()
logger = logging.getLogger("uvicorn")

@router.post("/export/summary/word", response_class=Response)
def export_summary_to_word(
    *,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
    title: str,
    summary: str
) -> Any:
    """
    Export a summary to Word (DOCX) format using the enhanced exporter
    
    Args:
        title: Document title
        summary: Summary text
        
    Returns:
        Word document as download
    """
    try:
        logger.info(f"Exporting summary to Word: {title}")
        
        # Create metadata
        metadata = {
            "Author": current_user.username,
            "Date": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "Generated by": "GRANTHIK AI"
        }
        
        # Create Word document
        docx_bytes = create_summary_docx(
            title=title,
            summary_text=summary,
            metadata=metadata
        )
        
        # Create filename
        safe_title = "".join(c for c in title if c.isalnum() or c in " _-").strip()
        safe_title = safe_title.replace(" ", "_")
        
        # Return file for download
        return Response(
            content=docx_bytes,
            media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            headers={
                "Content-Disposition": f'attachment; filename="{safe_title}.docx"'
            }
        )
    
    except Exception as e:
        logger.error(f"Error exporting summary to Word: {str(e)}")
        raise HTTPException(
            status_code=500,
            detail="Failed to export summary to Word"
        )